runtime: python39 # or another supported version
instance_class: F1
runtime: python39
entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2


handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto